# Stage 1 - the build process
FROM node:alpine as builder

RUN mkdir -p /usr/src/builder

WORKDIR /usr/src/builder

ARG PORT
ARG MONGO_URI
ARG MONGO_USER
ARG MONGO_PASS
ARG MICROSERVICE_SECRET
ARG AUTH_SERVICE_URI

ENV PORT=$PORT
ENV MONGO_URI=$MONGO_URI
ENV MONGO_USER=$MONGO_USER
ENV MONGO_PASS=$MONGO_PASS
ENV MICROSERVICE_SECRET=$MICROSERVICE_SECRET
ENV AUTH_SERVICE_URI=$AUTH_SERVICE_URI

COPY . .

RUN yarn install
RUN yarn run build
RUN rm -rf node_modules


# Stage 2 - the production environment
FROM keymetrics/pm2:latest-alpine
LABEL author="Ohm Piromrak"

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY --from=builder /usr/src/builder/build .

EXPOSE 3001

CMD ["pm2-runtime", "start", "index.js"]
